
services:
  php:
    build: .
    container_name: php_app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: Tchingjo12
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql  # Se connecte au service "mysql"
      MYSQL_ROOT_PASSWORD: Tchingjo12
    ports:
      - "8081:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data: