version: "3.8"

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=#Dev@1234.com
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  pgadmin-data: